# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: installNode
    displayName: 'Install Node.js'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.15.0'

  - job: RunNpmCi
    displayName: 'npm ci'
    dependsOn: installNode
    steps:
      - script: |
          npm ci
          npx cypress run --e2e --browser chrome
